# Generated by Django 5.0.6 on 2024-05-13 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editorprofile',
            name='social_links',
        ),
        migrations.AddField(
            model_name='editorprofile',
            name='social_links',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.sociallink'),
        ),
    ]
